import net.fabricmc.loom.configuration.ide.RunConfigSettings

plugins {
    id "fabric-loom" version "1.13.6"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    exclusiveContent {
        forRepository {
            maven {
                name = "CurseMaven"
                url = "https://cursemaven.com"
            }
        }

        filter {
            includeGroup "curse.maven"
        }
    }

    maven {
        name = "Ladysnake"
        url = "https://maven.ladysnake.org/releases"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.2"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.2"
    modImplementation "dev.emi:trinkets:${project.trinkets_version}"

    // for decompiling mixins when exported
    // runtimeOnly "org.vineflower:vineflower:1.11.2"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

fabricApi {
    configureDataGeneration()
}

loom {
    accessWidenerPath = file("src/main/resources/playercollars.accesswidener")

    runs {
        configureEach {
            property("mixin.dumpTargetOnFailure", "true")
            // property("mixin.debug.export", "true")
            property("mixin.hotSwap", "true")
            property("sodium.checks.issue2561", "false")
        }

        named { !it.contains("Two") && !it.contains("datagen") }.all { RunConfigSettings parent ->
            def name = "${parent.name}Two"
            loom.runConfigs.create(name) {
                inherit(parent)
                runDir("run2")
            }
        }
    }
}

// necessary for mixin hotswapping
afterEvaluate {
    loom {
        runs {
            configureEach {
                def runtimeClasspath = project.configurations.named("runtimeClasspath")
                def mixinJarFile = runtimeClasspath.get().resolvedConfiguration.resolvedArtifacts.find {
                    def module = it.moduleVersion.id
                    return module.group == "net.fabricmc" && module.name == "sponge-mixin"
                }
                if (mixinJarFile != null)
                    vmArg("-javaagent:${mixinJarFile.file}")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    exclude("org/jlortiz/playercollars/datagen/**")
    exclude("assets/playercollars/lang/en_us.existing.json")
}
