modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.playercollars]]
    modId="forge"
    mandatory=true
    versionRange="[47.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playercollars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playercollars]]
    modId="curios"
    mandatory=true
    versionRange="[5.9,)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
modId="playercollars"
version="${version}"
displayName="Player Collars"
description='''
Lets players wear pet collars.
Leashable players code from https://modrinth.com/mod/leashable-players
Collar model derived from https://www.curseforge.com/minecraft/mc-mods/player-collars
'''
